name = "chick-fil-gay-api"
type = "javascript"
main = "./functions/index.ts"
compatibility_date = "2025-06-22"

[vars]
PLAID_CLIENT_ID = "${PLAID_CLIENT_ID}"
PLAID_SECRET = "${PLAID_SECRET}"
PLAID_ENV = "${PLAID_ENV}"
STRIPE_SECRET_KEY = "${STRIPE_SECRET_KEY}"
STRIPE_WEBHOOK_SECRET = "${STRIPE_WEBHOOK_SECRET}"

[env.production.vars]
# Set production secrets in your Cloudflare dashboard or GitHub Actions

[build]
command = "pnpm install && pnpm build"
